In [12]:
(Xe, Ye, nC, L, particulas, max_iteraciones,C) = preproceso()


 estos deberian ser los datos antes de normalizarlos [[0.0e+00 1.0e+00 1.0e+00 ... 0.0e+00 5.0e-02 0.0e+00]
 [0.0e+00 2.0e+00 2.0e+00 ... 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 1.0e+00 3.0e+00 ... 1.0e+00 0.0e+00 0.0e+00]
 ...
 [0.0e+00 1.0e+00 3.0e+00 ... 0.0e+00 1.0e+00 1.0e+00]
 [0.0e+00 1.0e+00 5.5e+01 ... 1.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 1.0e+00 1.1e+01 ... 1.0e+00 0.0e+00 0.0e+00]]

 estos deberian ser los datos normalizados [[0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.10000003 0.10000003 0.10000003 ... 0.10000003 0.10000003 0.10000003]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
[ 1  1 -1 ... -1 -1 -1]
[[0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.1        0.1        0

In [7]:
import numpy as np
import funciones as fp

##Cambio de datos
##Data[1]
data1 = ['tcp', 'udp', 'icmp']  
data2 = ['ftp_data', 'other', 'private', 'http', 'remote_job', 'name', 'netbios_ns', 'eco_i', 'mtp', 'telnet', 'finger', 'domain_u', 'supdup', 'uucp_path', 'Z39_50', 'smtp', 'csnet_ns', 'uucp', 'netbios_dgm', 'urp_i', 'auth', 'domain', 'ftp', 'bgp', 'ldap', 'ecr_i', 'gopher', 'vmnet', 'systat', 'http_443', 'efs', 'whois', 'imap4', 'iso_tsap', 'echo', 'klogin', 'link', 'sunrpc', 'login', 'kshell', 'sql_net', 'time', 'hostnames', 'exec', 'ntp_u', 'discard', 'nntp', 'courier', 'ctf', 'ssh', 'daytime', 'shell', 'netstat', 'pop_3', 'nnsp', 'IRC', 'pop_2', 'printer', 'tim_i', 'pm_dump', 'red_i', 'netbios_ssn', 'rje', 'X11', 'urh_i', 'http_8001']
data3 = ['SF', 'S0', 'REJ', 'RSTR', 'SH', 'RSTO', 'S1', 'RSTOS0', 'S3', 'S2', 'OTH']
data41 = ['normal', 'neptune', 'warezclient', 'ipsweep', 'portsweep', 'teardrop', 'nmap', 'satan', 'smurf', 'pod', 'back', 'guess_passwd', 'ftp_write', 'multihop', 'rootkit', 'buffer_overflow', 'imap', 'warezmaster', 'phf', 'land', 'loadmodule', 'spy']

def transform (data,lista):
    contador=0
    if lista == 1:    
        for i in data1:
            if str(i) == data:
                return contador+1
            contador+=1
    if lista == 2:
        for i in data2:
            if str(i) == data:
                return contador+1
            contador+=1
    if lista == 3:
        for i in data3:
            if str(i) == data:
                return contador+1
            contador+=1
    if lista == 4:
        if str(data) != 'normal':
            return -1
        return 1

In [8]:
def load_config():
	config = np.genfromtxt("configuracion.csv", dtype=float, delimiter='\n') 
	#VECTOR[ ]
	nc=1
	#Nodos ocultos
	L=config[0]
	#Particulas
	particulas=config[1]
	#Maximo de iteraciones
	max_iteraciones=config[2]
	#Penalidad P inversa
	C=config[3]
	return (nc,L,particulas,max_iteraciones,C)
	

In [9]:
#param: dato[][]
def Normalize_Xe(datos):
    y = np.empty_like(datos)
    
    #x_min, x_max deben ser int, datos debe ser una matriz de int
    x_min = np.min(datos)
    x_max = np.max(datos)
    print("\n estos deberian ser los datos antes de normalizarlos", datos)
    for data in datos: 
        contador = 0
        for i in data:
            #aux=str(i);
            x = i.astype(float)
            y[contador] = (x-x_min)/(x_max-x_min)
            #y[contador]=(0.99-0.1)*y[contador]+0.1
            contador+=1
    
   # normal =np.linalg.norm(data_normal)
   # print (normal)
    print("\n estos deberian ser los datos normalizados", y)
    
    return y



In [10]:
def to_readable(path,name):
    datos = np.loadtxt(path, delimiter=',',dtype='str',usecols=(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40))

    #Se transforma todo a numeros enteros.
    for data in datos:
        contador=0
        for i in data:
            if contador == 1:
                data[contador]=transform(str(i),1)
            if contador == 2:
                data[contador]=transform(str(i),2)
            if contador == 3:
                data[contador]=transform(str(i),3)
            contador+=1
    datos = datos.astype(np.float)
    datos=Normalize_Xe(datos)
    #Se escribe el archivo nuevo
    np.savetxt(name, datos, delimiter=',')
    
    Y=np.loadtxt(path, delimiter=',',dtype='str',usecols=41)
    Yee=[]
    for data in Y:
        if data != 'normal':
            Yee.append(-1)
        else:
            Yee.append(1)
    Ye=np.array(Yee)
    return Ye


In [11]:
def preproceso():
    Ye=to_readable("KDDTrain+_20Percent.txt","train.txt")
    Xe=np.loadtxt("train.txt", delimiter=',',dtype='float', usecols=(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40))
    (nC,L,particulas,max_iteraciones,C)=load_config()
    print (Ye)
    print (Xe)
    
    return (Xe, Ye, nC, L, particulas, max_iteraciones,C)

In [131]:
import math
def random_w(L,Dim):
    l=int(L)
    w =np.empty([l+1,Dim])
    for i in range (l+1):
        contador = 0
        #print(i)
        for j in range(Dim):
            r=math.sqrt(6/((L+1) + Dim))
            #np.append(w, r)
            w[i][j]=np.random.uniform(L,Dim)*2*r-r;
            contador+=1
    #int or float or something
    return w

In [222]:
def update_pesos(Xe,Ye,L,C):
    #[Filas] 
    Dim=Xe.shape[0]
    #[Columnas]
    n=Xe.shape[1]
    #print(n)
    print("Xe shape 0: y 1",Dim,n)
    #Pesos
    w1 =random_w(L,Dim)
   # w1 = np.transpose(w1)
    print("Dimensiones de los pesos w1:", w1.shape[0]," y ",w1.shape[1])
    #print()
    #Vector de pesos
    bias =random_w(L,1)

    print("Dimensiones de bias:", bias.shape[0]," y ",bias.shape[1])
    #print(bias)
    #print()
    #Matriz de vector de pesos
    biasMatrix =np.matlib.repmat(bias,1,n)
    print("Dimensiones de biasMatrix:", biasMatrix.shape[0]," y ",biasMatrix.shape[1])

    #print(biasMatrix)
    z=np.dot(w1,Xe)+biasMatrix
    print (Xe)
    print(z)
    H=activacion(Xe,w1)
    
    yh=Ye*H
    print("Ye es igual a: ",Ye.shape[0])
    print("H es igual a D: :",H.shape[0])
    hh=(H*np.transpose(H))+np.eye(int(L))/C
    inv=np.linalg.pinv(hh)
    w2=np.dot(yh,inv)
    return(w1, bias, w2)

In [223]:
def forward(xv, w1, bias, w2):
    N= len(xv)
    biasMatrix = np.matlib.repmat(bias,1,N)
    z = w1*xv +biasMatrix
    H = activacion(z);
    z=w2*H;
    return z

In [224]:
def activacion(x,w):
    print("Shape 0 x :",x.shape[0])
    print("Shape 1 x :",x.shape[1])
    print("Shape 0 w :",w.shape[0])
    print("Shape 1 w :",w.shape[1])
    aux = []
    for i in range(x.shape[0]):
        for j in range(w.shape[1]):
           # print("x en activacion",x[i])
           # print("y en activacion",w[:,j])
            z=distancia_euclidiana(x[i],w[:,j])
            H=np.cos(5*z)*np.exp(-0.5*z**2)
            continue
        return H

In [225]:
def distancia_euclidiana(x,y):
   # print ("Range x 0 y Range y 0 :",len(x),len(y))
    #for i in 
    distancia = math.sqrt(sum([(a-b) ** 2 for a,b in zip(x,y)]))
    return distancia

In [226]:
(w1,bias,w2) = update_pesos(Xe,Ye,L,C)

Xe shape 0: y 1 25192 41
Dimensiones de los pesos w1: 41  y  25192
Dimensiones de bias: 41  y  1
Dimensiones de biasMatrix: 41  y  41
[[0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.10000003 0.10000003 0.10000003 ... 0.10000003 0.10000003 0.10000003]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
[[1476.45521065 1476.45521065 1476.45521065 ... 1476.45521065
  1476.45521065 1476.45521065]
 [1334.54495905 1334.54495905 1334.54495905 ... 1334.54495905
  1334.54495905 1334.54495905]
 [1612.19578654 1612.19578654 1612.19578654 ... 1612.19578654
  1612.19578654 1612.19578654]
 ...
 [1770.74705909 1770.74705909 1770.74705909 ... 1770.74705909
  1770.74705909 1770.74705909]
 [1607.54006057 1607.54006057 1607.54006057 .

IndexError: tuple index out of range